# Generated by Django 3.1.2 on 2021-01-05 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0025_auto_20210103_0808'),
        ('api', '0045_delete_userselectedkpis'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_users', to='api.account'),
        ),
        migrations.CreateModel(
            name='UserSelectedKPIs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_kpis', models.ManyToManyField(to='configurations.KPI')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_selected_kpis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "User's selected KPIs",
                'verbose_name_plural': 'Users Selected KPIs Table',
            },
        ),
    ]
