# Generated by Django 3.1.2 on 2020-11-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201116_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='milking',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
