# Generated by Django 3.1.2 on 2020-11-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201116_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='milking',
            field=models.BooleanField(default=False, help_text='<p style="color:tomato;font-family:georgia,garamond,serif;font-size:16px;font-style:italic;">auto updates by using one of the specified names: <br> &nbsp;&nbsp;&nbsp;&nbsp; MILKING NAMES: Milking, Default <br> &nbsp;&nbsp;&nbsp;&nbsp; NOT MILKING: Dry, DryBranch, Heifers. <br> if a name is not in either of the lists, defaults to False</p>'),
            preserve_default=False,
        ),
    ]
