# Generated by Django 3.1.2 on 2020-11-17 06:34

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201116_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='farm_name',
        ),
        migrations.AlterField(
            model_name='farm',
            name='daily_rumination_ranges',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), default=[30, 20, 10], size=3),
        ),
    ]
