# Generated by Django 3.1.2 on 2020-11-17 08:15

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201117_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='daily_rumination_ranges',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, default=[30, 20, 10], null=True, size=3),
        ),
        migrations.AlterField(
            model_name='farm',
            name='farm_size',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, default=[10, 20, 30, 40], null=True, size=4),
        ),
        migrations.AlterField(
            model_name='farm',
            name='health_rate_ranges',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, default=[10, 20, 30], null=True, size=3),
        ),
        migrations.AlterField(
            model_name='farm',
            name='system_key',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='farm',
            name='ten_days_avg_rumination_ranges',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, default=[10, 20, 30], null=True, size=3),
        ),
        migrations.AlterField(
            model_name='farm',
            name='ten_days_rumination_ranges',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, default=[10, 20, 30], null=True, size=3),
        ),
    ]
