# Generated by Django 3.1.2 on 2020-11-17 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201117_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='admin_phone',
            field=models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
