# Generated by Django 3.1.2 on 2020-11-17 15:38

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20201117_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminConfigurationsLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_farm_size', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2, verbose_name='small farm size')),
                ('m_farm_size', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2, verbose_name='medium farm size')),
                ('l_farm_size', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2, verbose_name='large farm size')),
                ('xl_farm_size', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2, verbose_name='extra large farm size')),
                ('red_health_rate_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('yellow_health_rate_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('green_health_rate_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('red_daily_rumination_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('yellow_rumination_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('green_rumination_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('red_ten_days_rumination_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('yellow_ten_days_rumination_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('green_ten_days_rumination_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('red_ten_days_avg_rumination_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('yellow_ten_days_avg_rumination_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('green_ten_days_avg_rumination_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
            ],
            options={
                'verbose_name': 'Admin Configurations',
            },
        ),
        migrations.RemoveField(
            model_name='farm',
            name='daily_rumination_ranges',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='farm_size',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='health_rate_ranges',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='ten_days_avg_rumination_ranges',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='ten_days_rumination_ranges',
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(default='default_account', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='branchkpis',
            unique_together={('branch', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='farmkpis',
            unique_together={('farm', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='groupkpis',
            unique_together={('group', 'date')},
        ),
    ]
