# Generated by Django 3.1.2 on 2020-11-17 16:24

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20201117_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchConfigurationsLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_health_rate_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('yellow_health_rate_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('green_health_rate_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('red_daily_rumination_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('yellow_rumination_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('green_rumination_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('red_ten_days_rumination_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('yellow_ten_days_rumination_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('green_ten_days_rumination_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('red_ten_days_avg_rumination_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('yellow_ten_days_avg_rumination_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('green_ten_days_avg_rumination_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('level', models.IntegerField(choices=[(1, 'farm'), (2, 'group'), (2, 'group')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FarmConfigurationsLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_health_rate_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('yellow_health_rate_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('green_health_rate_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('red_daily_rumination_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('yellow_rumination_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('green_rumination_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('red_ten_days_rumination_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('yellow_ten_days_rumination_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('green_ten_days_rumination_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('red_ten_days_avg_rumination_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('yellow_ten_days_avg_rumination_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('green_ten_days_avg_rumination_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('level', models.IntegerField(choices=[(1, 'farm'), (2, 'group'), (2, 'group')])),
                ('s_farm_size', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2, verbose_name='small farm size')),
                ('m_farm_size', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2, verbose_name='medium farm size')),
                ('l_farm_size', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2, verbose_name='large farm size')),
                ('xl_farm_size', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2, verbose_name='extra large farm size')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupConfigurationsLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_health_rate_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('yellow_health_rate_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('green_health_rate_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('red_daily_rumination_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('yellow_rumination_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('green_rumination_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('red_ten_days_rumination_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('yellow_ten_days_rumination_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('green_ten_days_rumination_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('red_ten_days_avg_rumination_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('yellow_ten_days_avg_rumination_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('green_ten_days_avg_rumination_range', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=2)),
                ('level', models.IntegerField(choices=[(1, 'farm'), (2, 'group'), (2, 'group')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='AdminConfigurationsLayer',
        ),
    ]
