# Generated by Django 3.1.2 on 2020-11-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20201117_1624'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BranchConfigurationsLayer',
        ),
        migrations.DeleteModel(
            name='FarmConfigurationsLayer',
        ),
        migrations.DeleteModel(
            name='GroupConfigurationsLayer',
        ),
    ]
