# Generated by Django 3.1.2 on 2020-11-18 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20201117_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='daily_rumination_ranges',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='health_rate_ranges',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='ten_days_avg_rumination_ranges',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='ten_days_rumination_ranges',
        ),
        migrations.RemoveField(
            model_name='group',
            name='daily_rumination_ranges',
        ),
        migrations.RemoveField(
            model_name='group',
            name='health_rate_ranges',
        ),
        migrations.RemoveField(
            model_name='group',
            name='ten_days_avg_rumination_ranges',
        ),
        migrations.RemoveField(
            model_name='group',
            name='ten_days_rumination_ranges',
        ),
    ]
