# Generated by Django 3.1.2 on 2020-11-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20201118_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchkpis',
            name='daily_rumination_variability',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='branchkpis',
            name='health_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='farmkpis',
            name='daily_rumination_variability',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='farmkpis',
            name='health_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='groupkpis',
            name='daily_rumination_variability',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='groupkpis',
            name='health_score',
            field=models.IntegerField(default=0),
        ),
    ]
