# Generated by Django 3.1.2 on 2020-11-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20201119_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
