# Generated by Django 3.1.2 on 2020-11-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20201119_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmkpis',
            name='farm_size',
        ),
        migrations.AddField(
            model_name='account',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Farm Id'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Farm Name'),
        ),
    ]
