# Generated by Django 3.1.2 on 2020-12-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20201126_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.CharField(help_text='Account ID', max_length=100, primary_key=True, serialize=False),
        ),
    ]
