# Generated by Django 3.1.2 on 2020-12-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20201206_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='zoura_billing_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
