# Generated by Django 3.1.2 on 2020-12-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_account_zoura_billing_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
