# Generated by Django 3.1.2 on 2020-12-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_farm_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='system_key',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
