# Generated by Django 3.1.2 on 2020-12-09 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20201207_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupkpis',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_scores', to='api.group'),
        ),
    ]
