# Generated by Django 3.1.2 on 2020-12-10 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20201209_0631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='subscription_id',
            new_name='zoura_billing_account_id',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='zoura_billing_id',
            new_name='zoura_subscription_id',
        ),
    ]
