# Generated by Django 3.1.2 on 2020-12-23 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_kpi_kpisbundle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kpisbundle',
            options={'verbose_name': 'KPIs Bundle'},
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='bundle',
        ),
    ]
