# Generated by Django 3.1.2 on 2020-12-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20201223_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='bundle',
            field=models.ManyToManyField(blank=True, null=True, to='api.KPIsBundle'),
        ),
    ]
