# Generated by Django 3.1.2 on 2020-12-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_kpi_bundle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='bundles',
            field=models.ManyToManyField(to='api.KPIsBundle'),
        ),
        migrations.AddField(
            model_name='kpisbundle',
            name='shown_in',
            field=models.ManyToManyField(to='api.Screen'),
        ),
    ]
