# Generated by Django 3.1.2 on 2020-12-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20201223_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpisbundle',
            name='shown_in',
        ),
        migrations.AddField(
            model_name='kpi',
            name='shown_in',
            field=models.ManyToManyField(to='api.Screen'),
        ),
    ]
