# Generated by Django 3.1.2 on 2020-12-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20201223_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='bundle',
            field=models.ManyToManyField(blank=True, null=True, related_name='bundle_kpis', to='api.KPIsBundle'),
        ),
    ]
