# Generated by Django 3.1.2 on 2020-12-23 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20201223_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='bundles',
        ),
        migrations.DeleteModel(
            name='KPI',
        ),
        migrations.DeleteModel(
            name='KPIsBundle',
        ),
        migrations.DeleteModel(
            name='Screen',
        ),
    ]
