# Generated by Django 3.1.2 on 2020-12-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0016_auto_20201223_1356'),
        ('api', '0035_auto_20201223_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bundles',
            field=models.ManyToManyField(to='configurations.KPIsBundle'),
        ),
    ]
