# Generated by Django 3.1.2 on 2020-12-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_account_bundles'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
