# Generated by Django 3.1.2 on 2020-12-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0016_auto_20201223_1356'),
        ('api', '0037_account_first_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSelectedKPIs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_kpis', models.ManyToManyField(to='configurations.KPI')),
            ],
        ),
    ]
