# Generated by Django 3.1.2 on 2020-12-23 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_accountselectedkpis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountselectedkpis',
            options={'verbose_name': "User's selected KPIs", 'verbose_name_plural': 'Users Selected KPIs Table'},
        ),
        migrations.AddField(
            model_name='accountselectedkpis',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
    ]
