# Generated by Django 3.1.2 on 2020-12-24 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20201223_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='first_login',
        ),
    ]
