# Generated by Django 3.1.2 on 2020-12-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20201225_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchkpis',
            name='assigned_tag_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='branchkpis',
            name='cow_count',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='branchkpis',
            name='daily_rumination_variability',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='branchkpis',
            name='health_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='branchkpis',
            name='ten_days_average_rumination',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='branchkpis',
            name='ten_days_rumination_variability',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='farmkpis',
            name='assigned_tag_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='farmkpis',
            name='cow_count',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='farmkpis',
            name='daily_rumination_variability',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='farmkpis',
            name='health_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='farmkpis',
            name='ten_days_average_rumination',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='farmkpis',
            name='ten_days_rumination_variability',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='groupkpis',
            name='assigned_tag_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='groupkpis',
            name='cow_count',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='groupkpis',
            name='daily_rumination_variability',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='groupkpis',
            name='health_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='groupkpis',
            name='ten_days_average_rumination',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='groupkpis',
            name='ten_days_rumination_variability',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
