# Generated by Django 3.1.2 on 2021-01-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0025_auto_20210103_0808'),
        ('api', '0045_delete_userselectedkpis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bundles',
            field=models.ManyToManyField(related_name='bundles_by_account', to='configurations.KPIsBundle'),
        ),
    ]
