# Generated by Django 3.1.2 on 2021-01-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20210114_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='logo_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='show_logo',
            field=models.BooleanField(default=False),
        ),
    ]
