# Generated by Django 3.1.2 on 2020-11-30 13:54

import django.contrib.postgres.fields.hstore
import django.core.validators
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        HStoreExtension(),
        migrations.CreateModel(
            name='UsageReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tags_count', django.contrib.postgres.fields.hstore.HStoreField()),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1),
                                                          django.core.validators.MaxValueValidator(12)])),
                ('year', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('zoura_import_status_url', models.URLField()),
            ],
        ),
    ]
