# Generated by Django 3.1.2 on 2020-12-02 09:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20201126_1250'),
        ('account_management_api', '0002_auto_20201202_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmMonthlyUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags_count', models.IntegerField()),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.farm')),
            ],
            options={
                'verbose_name': 'Farm Monthly Usage Report',
                'verbose_name_plural': 'Farms Monthly Usage Reports',
            },
        ),
    ]
