# Generated by Django 3.1.2 on 2020-12-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management_api', '0003_farmmonthlyusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagereports',
            name='successfully_sent',
            field=models.BooleanField(default=True, help_text="When we send the request, if it wasn't successful, we'll try again day after"),
        ),
        migrations.AlterField(
            model_name='farmmonthlyusage',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
