# Generated by Django 3.1.2 on 2020-12-02 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20201126_1250'),
        ('account_management_api', '0004_auto_20201202_1344'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='farmmonthlyusage',
            unique_together={('date', 'farm')},
        ),
        migrations.AlterUniqueTogether(
            name='usagereports',
            unique_together={('date', 'zoura_import_status_url')},
        ),
    ]
