# Generated by Django 3.1.2 on 2020-12-03 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_management_api', '0005_auto_20201202_1402'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='farmmonthlyusage',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='farmmonthlyusage',
            name='farm',
        ),
        migrations.DeleteModel(
            name='UsageReports',
        ),
        migrations.DeleteModel(
            name='FarmMonthlyUsage',
        ),
    ]
