# Generated by Django 3.1.2 on 2020-12-03 08:56

import django.contrib.postgres.fields.hstore
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0021_auto_20201126_1250'),
        ('account_management_api', '0006_auto_20201203_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tags_count', django.contrib.postgres.fields.hstore.HStoreField()),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('zoura_import_status_url', models.URLField()),
                ('successfully_sent', models.BooleanField(default=True, help_text="When we send the request, if it wasn't successful, we'll try again day after")),
            ],
            options={
                'verbose_name': 'Monthly Usage Report',
                'verbose_name_plural': 'Monthly Usage Reports',
                'unique_together': {('date', 'zoura_import_status_url')},
            },
        ),
        migrations.CreateModel(
            name='FarmMonthlyUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags_count', models.IntegerField()),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.IntegerField()),
                ('date', models.DateField(null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.farm')),
            ],
            options={
                'verbose_name': 'Farm Monthly Usage Report',
                'verbose_name_plural': 'Farms Monthly Usage Reports',
                'unique_together': {('date', 'farm')},
            },
        ),
    ]
