# Generated by Django 3.1.2 on 2020-12-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management_api', '0007_farmmonthlyusage_usagereports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usagereports',
            name='total_tags_count',
        ),
        migrations.AddField(
            model_name='usagereports',
            name='file',
            field=models.TextField(default='', help_text='CSV format of the file'),
            preserve_default=False,
        ),
    ]
