# Generated by Django 3.1.2 on 2020-12-08 09:10

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_management_api', '0009_salesforceapikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagereports',
            name='file',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(), default=list, help_text='CSV format of the file', size=None),
        ),
    ]
